### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by ddnexus** [bmalehorn/vscode-shell-syntax#3]
VIsual Studio Code 1.50.1 Ubuntu 20.10: it does not do anything in zsh files. 
Did I miss something?

**Comment by bmalehorn** [comment]
@ddnexus:
1. what is the filename of the file you're trying to edit?
2. what error are you trying to highlight?
3. do you have `zsh` installed? You need to have it installed, which you can do with `sudo apt-get install zsh`

Here's what I tried:

1. `code ~/.zshrc`
2. added an unmatched `fi`

this successfully highlighted the syntax error:

![image](https://user-images.githubusercontent.com/3344958/98760009-2861fe80-2387-11eb-9bd9-d5bd905458df.png)

**Comment by ddnexus** [comment]
Thanks for the answer. 

Yes, of course `zsh`is installed and well since at least 6 years :). 

I've just tried the same you shown in `~/.zshrc` with an extra `fi` or in whatever file `*.zsh`. The shebang is there in all files. It does not highlight anything, and it does not work with any other bad syntax AFAIK. 

VSC behave the same with or without the extension. I tried to uninstall and re-install it and it does not change anything.

Also I tried to disable most other extensions but nothing changes. How can we debug it?

**Comment by ddnexus** [comment]
D'oh! :facepalm: 

I am used to the Jetbrains tools (e.g. RubyMine, PyCharm, WebStorm, etc.) that highlight the syntax error on typing. Since I am quite new to VSC and your extension, I didn't think I have to save it in order to see the syntax problems.

You are checking the saved file, not the editor buffer, and that's not so obvious for someone used to other tools. 
Maybe mentioning that it checks on save would be useful to others.

Thank you!

**Comment by bmalehorn** [comment]
Yep, that's exactly it. I've updated to README to include a disclaimer that it happens "on save".

I tried looking into getting this to run as you're typing, but ran into some issues with linting a modified document. Not sure why, but I think the current iteration is fine so :shrug:

**Comment by ddnexus** [comment]
Yeah... better than nothing :smile: 
Thank you!
