### ISSUE TITLE
Setting to specify default shell

### ISSUE THREAD

**Issue by marlonrichert** [bmalehorn/vscode-shell-syntax#7]
Function files distributed with Zsh don't have filename extensions nor shebangs. When I'm editing functions in [the Zsh repository](https://github.com/zsh-users/zsh), Shell Syntax treats these as Bash scripts, causing many false positives. I would like to be able to tell Shell Syntax to treat all unidentified shell scripts as Zsh, not Bash.

**Comment by bmalehorn** [comment]
@marlonrichert Thanks for trying out the extension. It is true that if you're editing a shell script without an obvious syntax that it assumes you're writing `bash`.

I'm wondering, how are you telling vscode that you're editing a shell script at all? When I open files in that repo, they aren't highlighted as anything:

![image](https://user-images.githubusercontent.com/3344958/125178117-89e8a000-e196-11eb-8886-ae7783fe7b6a.png)

**Comment by marlonrichert** [comment]
> I'm wondering, how are you telling vscode that you're editing a shell script at all?

```json
"files.associations": {
  "*": "shellscript",
  "*.c": "c",
  "*.yo": "plaintext"
}
```

**Comment by bmalehorn** [comment]
Hi @marlonrichert, I've added a new config option to specify a shell when nothing else is detected:

```json
"shell-syntax.defaultShell": "zsh",
```

Would you mind trying it out and let me know if it works?

Overall I think it makes sense to add this option, since the choice of bash is somewhat arbitrary.

**Comment by marlonrichert** [comment]
Seems to work at first glance. 👍🏽 I'll let you know if I run into problems.
